### ISSUE TITLE
Error when creating a recipe

### ISSUE THREAD

**Issue by alg** [peritor/webistrano#2]
Here's what I get when creating a new recipe:

NoMethodError (undefined method `detect' for nil:NilClass):
    /vendor/plugins/version_fu/lib/version_fu.rb:98:in`create_new_version?'
    /vendor/plugins/version_fu/lib/version_fu.rb:91:in `check_for_new_version'
    /vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in`send'
    /vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in `evaluate_method'
    /vendor/rails/activesupport/lib/active_support/callbacks.rb:166:in`call'
    /vendor/rails/activesupport/lib/active_support/callbacks.rb:93:in `run'
    /vendor/rails/activesupport/lib/active_support/callbacks.rb:92:in`each'
    /vendor/rails/activesupport/lib/active_support/callbacks.rb:92:in `send'
    /vendor/rails/activesupport/lib/active_support/callbacks.rb:92:in`run'
    /vendor/rails/activesupport/lib/active_support/callbacks.rb:277:in `run_callbacks'
    /vendor/rails/activerecord/lib/active_record/callbacks.rb:315:in`callback'
    /vendor/rails/activerecord/lib/active_record/callbacks.rb:221:in `create_or_update'
    /vendor/rails/activerecord/lib/active_record/base.rb:2383:in`save_without_validation'
    /vendor/rails/activerecord/lib/active_record/validations.rb:1009:in `save_without_dirty'
    /vendor/rails/activerecord/lib/active_record/dirty.rb:79:in`save_without_transactions'
    /vendor/rails/activerecord/lib/active_record/transactions.rb:179:in `send'
    /vendor/rails/activerecord/lib/active_record/transactions.rb:179:in`with_transaction_returning_status'
    /vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `transaction'
    /vendor/rails/activerecord/lib/active_record/transactions.rb:129:in`transaction'
    /vendor/rails/activerecord/lib/active_record/transactions.rb:138:in `transaction'
    /vendor/rails/activerecord/lib/active_record/transactions.rb:178:in`with_transaction_returning_status'
    /vendor/rails/activerecord/lib/active_record/transactions.rb:146:in `save'
    /vendor/rails/activerecord/lib/active_record/transactions.rb:158:in`rollback_active_record_state!'
    /vendor/rails/activerecord/lib/active_record/transactions.rb:146:in `save'
    /app/controllers/recipes_controller.rb:42:in`create'

**Comment by jweiss** [comment]
Can you please try the development version from github?

**Comment by alg** [comment]
It was fresh dev version from github. I can see you didn't update it today, so there's no reason to pull the updates for me.

**Comment by jweiss** [comment]
Are you sure that you use a recent checkout? I've just checked out a fresh copy, created a mysql db and migrated. Then I created a recipe and everything worked fine.

**Comment by alg** [comment]
Yup, I am:

  [root@www webistrano]# git remote show origin
- remote origin
  Fetch URL: git://github.com/peritor/webistrano.git
  Push  URL: git://github.com/peritor/webistrano.git
  HEAD branch: master
  ...
  
  [root@www webistrano]# git pull
    Already up-to-date.

**Comment by alg** [comment]
[alg@www ~]$ ruby -v
  ruby 1.8.6 (2008-08-11 patchlevel 287) [i686-linux]
  Ruby Enterprise Edition 20090610

  [alg@www ~]$ mysql --version
  mysql  Ver 14.12 Distrib 5.0.77, for redhat-linux-gnu (i686) using readline 5.1

**Comment by siemieniec** [comment]
Just experienced the same problem and fixed it with apache restart.
