### ISSUE TITLE
We're sorry, but something went wrong

### ISSUE THREAD

**Issue by guoxd** [peritor/webistrano#21]
tody, i opened the cap ,found that :We've been notified about this issue and we'll take a look at it shortly.
so, how can i deal this problem, i need cap to wok............

**Comment by jweiss** [comment]
did you look at the log files?

**Comment by damacus** [comment]
I presume that webistrano needs an old version of active_record anyone have any idea which version is needed?

Log File:

# Logfile created on 2012-02-10 15:14:38 +0000

NoMethodError (Attempt to call private method):
  vendor/bundler/ruby/1.9.1/gems/activerecord-2.3.11/lib/active_record/attribute_methods.rb:236:in `method_missing'
  lib/webistrano/deployer.rb:25:in`initialize'
  app/models/stage.rb:125:in `new'
  app/models/stage.rb:125:in`list_tasks'
  app/controllers/stages_controller.rb:17:in `show'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/base.rb:1333:in`perform_action'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/filters.rb:617:in `call_filters'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/filters.rb:638:in`block in run_before_filters'
  app/controllers/application_controller.rb:24:in `set_timezone'
  vendor/bundler/ruby/1.9.1/gems/activesupport-2.3.11/lib/active_support/callbacks.rb:178:in`evaluate_method'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/filters.rb:186:in `call'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/filters.rb:635:in`run_before_filters'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/filters.rb:615:in `call_filters'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/filters.rb:610:in`perform_action_with_filters'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/benchmarking.rb:68:in `block in perform_action_with_benchmark'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/benchmarking.rb:68:in`perform_action_with_benchmark'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/rescue.rb:160:in `perform_action_with_rescue'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/flash.rb:151:in`perform_action_with_flash'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/base.rb:532:in `process'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/filters.rb:606:in`process_with_filters'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/base.rb:391:in `process'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/base.rb:386:in`call'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:438:in `call'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/dispatcher.rb:87:in`dispatch'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/dispatcher.rb:121:in `_call'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/dispatcher.rb:130:in`block in build_middleware_stack'
  vendor/bundler/ruby/1.9.1/gems/activerecord-2.3.11/lib/active_record/query_cache.rb:29:in `call'
  vendor/bundler/ruby/1.9.1/gems/activerecord-2.3.11/lib/active_record/query_cache.rb:29:in`block in call'
  vendor/bundler/ruby/1.9.1/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
  vendor/bundler/ruby/1.9.1/gems/activerecord-2.3.11/lib/active_record/query_cache.rb:9:in`cache'
  vendor/bundler/ruby/1.9.1/gems/activerecord-2.3.11/lib/active_record/query_cache.rb:28:in `call'
  vendor/bundler/ruby/1.9.1/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in`call'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/string_coercion.rb:25:in `call'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/params_parser.rb:15:in`call'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/session/cookie_store.rb:99:in `call'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/failsafe.rb:26:in`call'
  internal:prelude:10:in `synchronize'
  vendor/bundler/ruby/1.9.1/gems/actionpack-2.3.11/lib/action_controller/dispatcher.rb:106:in`call'
  vendor/bundler/ruby/1.9.1/gems/rails-2.3.11/lib/rails/rack/static.rb:31:in `call'
  vendor/bundler/ruby/1.9.1/gems/rails-2.3.11/lib/rails/rack/log_tailer.rb:17:in`call'
  /home/ec2-user/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  /home/ec2-user/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/webrick/httpserver.rb:94:in`run'
  /home/ec2-user/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

**Comment by jweiss** [comment]
Webistrano (or better - its dependencies) doesn't work with Ruby 1.9 yet

**Comment by damacus** [comment]
Right... do we/you know which particular dependency doesn't work with 1.9 yet? And is there any planned support for it in the future?

**Comment by jweiss** [comment]
Webistrano in general needs to be updated to the latest Rails. This will then also solve the 1.9 issue.

**Comment by davidlbatey** [comment]
Guys check out https://github.com/joelmoss/strano it uses rails 3.2 and looks really nice (not used it yet)

**Comment by damacus** [comment]
@davidlbatey so close to what we need. Sadly we're using PHP and SVN in house.
