### ISSUE TITLE
rake db:migrate fails due to undefined method `symlink' for class `Capistrano::Configuration::Namespaces::Namespace'

### ISSUE THREAD

**Issue by kevindew** [peritor/webistrano#30]
I got this when I updated my version of webistrano and tried to migrate. To verify it wasn't a customisation of my fork I also tried doing a fresh clone, bundle install and tried to migrate and got the same error. 

Quick work around to migrate without error is to just remove undef :symlink from config/initializers/capistrano_namespace_rake_fix.rb but naturally that must have been added for a reason.

Stack trace:

RAILS_ENV=production rake db:migrate --trace
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
undefined method `symlink' for class`Capistrano::Configuration::Namespaces::Namespace'
/Users/kev/Sites/webistrano-original/config/initializers/capistrano_namespace_rake_fix.rb:2
/Users/kev/Sites/webistrano-original/config/initializers/capistrano_namespace_rake_fix.rb:2:in `class_eval'
/Users/kev/Sites/webistrano-original/config/initializers/capistrano_namespace_rake_fix.rb:2
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:173:in`load_without_new_constant_marking'
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:173:in `load'
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:622:in`load_application_initializers'
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:621:in `each'
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:621:in`load_application_initializers'
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:176:in `process'
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in`send'
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in `run'
/Users/kev/Sites/webistrano-original/config/environment.rb:16
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in`require'
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require'
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in`new_constants_in'
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require'
/Users/kev/Sites/webistrano-original/vendor/bundler/ruby/1.8/gems/rails-2.3.11/lib/tasks/misc.rake:4
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:205:in`call'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:205:in `execute'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:200:in`each'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:200:in `execute'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:158:in`invoke_with_call_chain'
/opt/local/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:151:in`invoke_with_call_chain'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:176:in `invoke_prerequisites'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:174:in`each'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:174:in `invoke_prerequisites'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:157:in`invoke_with_call_chain'
/opt/local/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:151:in`invoke_with_call_chain'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/task.rb:144:in `invoke'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/application.rb:112:in`invoke_task'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/application.rb:90:in `top_level'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/application.rb:90:in`each'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/application.rb:90:in `top_level'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/application.rb:129:in`standard_exception_handling'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/application.rb:84:in `top_level'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/application.rb:62:in`run'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/application.rb:129:in `standard_exception_handling'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/lib/rake/application.rb:59:in`run'
/opt/local/lib/ruby/gems/1.8/gems/rake-0.9.0/bin/rake:31
/opt/local/bin/rake:19:in `load'
/opt/local/bin/rake:19
Tasks: TOP => db:migrate => environment

**Comment by kevindew** [comment]
I seem to get this problem starting the app as well.

**Comment by caiosba** [comment]
It worked for me by removing config/initializers/capistrano_namespace_rake_fix.rb. Looks like this fix is not necessary anymore.
