### ISSUE TITLE
Upgrade from 1.2 to 1.5 fails

### ISSUE THREAD

**Issue by digitaria** [peritor/webistrano#9]
We have experienced an issue upgrading from 1.2 to 1.5. The code was checked out on a new server, 
the database was dumped and loaded on the new server. The migrations were run. All dependencies are installed.

Webistrano runs, but when you go to deploy, the following is output to the web interface "Log":

<pre>
*** is not a class/module
*** /var/www/deploy/webistrano/app/models/project.rb:31:in `tasks'
*** /var/www/deploy/webistrano/vendor/rails/activerecord/lib/active_record/associations/association_proxy.rb:217:in `send'
*** /var/www/deploy/webistrano/vendor/rails/activerecord/lib/active_record/associations/association_proxy.rb:217:in `method_missing'
*** /var/www/deploy/webistrano/lib/webistrano/deployer.rb:160:in `load_project_template_tasks'
*** /var/www/deploy/webistrano/lib/webistrano/deployer.rb:118:in `set_up_config'
*** /var/www/deploy/webistrano/lib/webistrano/deployer.rb:65:in `execute!'
*** /var/www/deploy/webistrano/lib/webistrano/deployer.rb:62:in `catch'
*** /var/www/deploy/webistrano/lib/webistrano/deployer.rb:62:in `execute!'
*** /var/www/deploy/webistrano/lib/webistrano/deployer.rb:46:in `invoke_task!'
*** (eval):1
*** /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `eval'
*** /var/www/deploy/webistrano/vendor/rails/railties/lib/commands/runner.rb:48
*** /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
*** /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
*** script/runner:3
</pre>

The server logs have nothing. This is the only helpful output we can gather.

**Comment by digitaria** [comment]
By the way, we're running the most recent code:

<pre>
git remote show origin * remote origin
* remote origin
  Fetch URL: http://github.com/peritor/webistrano.git
  Push  URL: http://github.com/peritor/webistrano.git
</pre>


With Rails 2.3.5 and ruby 1.8.7 on Ubuntu.

**Comment by bradly** [comment]
I would check that all your templates are available on the new server :)
`Project.all.collect(&:template).uniq - ProjectConfiguration.templates.keys`

**Comment by digitaria** [comment]
That was it. Thank you.
